[package]
name = "eetf"
version = "0.3.3"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "Library for encoding/decoding Erlang External Term Format"
documentation = "http://sile.github.io/rustdocs/eetf/eetf/"
homepage = "https://github.com/sile/eetf"
repository = "https://github.com/sile/eetf"
readme = "README.md"
keywords = ["erlang"]
license = "MIT"

[dependencies]
num = "0.1"
byteorder = "0.5"
flate2 = "0.2"
